# Generated by Django 5.0.3 on 2024-03-18 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Phonenumber', models.IntegerField()),
                ('Password', models.CharField(max_length=20, null=True)),
                ('Image', models.ImageField(null=True, upload_to='Image')),
                ('Address', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('ambassador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
