# Generated by Django 5.0.3 on 2024-03-18 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='Image')),
                ('des', models.CharField(max_length=200, null=True)),
                ('dis', models.CharField(max_length=200, null=True)),
                ('ambassador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ambassador')),
            ],
        ),
    ]
