# Generated by Django 5.0.3 on 2024-03-18 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
        ),
    ]
