# Generated by Django 5.0.3 on 2024-03-19 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_book_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.CharField(max_length=100)),
                ('utype', models.CharField(max_length=100)),
                ('guideid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guide')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
