# Generated by Django 5.0.3 on 2024-04-02 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ambassador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ambassador'),
        ),
    ]
