# Generated by Django 5.0.3 on 2024-04-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_feedback_ambassador'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.article'),
        ),
    ]
