# Generated by Django 5.0.3 on 2024-04-03 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_feedback_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('sdate', models.DateField(null=True)),
                ('edate', models.DateField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='Image')),
                ('food', models.CharField(max_length=200, null=True)),
                ('dis', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.guide')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
