# Generated by Django 5.0.3 on 2024-04-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='fee',
            field=models.IntegerField(null=True),
        ),
    ]
