# Generated by Django 5.0.3 on 2024-04-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_events_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
    ]
