# Generated by Django 5.0.3 on 2024-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_events_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
