# Generated by Django 5.0.3 on 2024-04-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.events'),
        ),
    ]
